prefix-dev/rattler-build

docs/highlevel.md
src/main.rs

This comes in handy when testing ros packages

feat: add --channel to the cli so the users can add the needed channels

---

src/source.rs

My bad there was no canonicalization of the path. 
closes #140

fix: relative git_url paths

---

src/render/resolved_dependencies.rs

fix variants with version spec

---

Cargo.lock
Cargo.toml
src/main.rs

enable `--version` and `-V` flags

---

examples/rich/recipe.yaml

Helped with an issue I was having in https://github.com/prefix-dev/rattler-build/issues/161

bump rich version in example

---

Cargo.lock
Cargo.toml
src/env_vars.rs
src/packaging.rs
src/render/solver.rs
src/test.rs

Bumps to rattler [v0.6.0](https://github.com/mamba-org/rattler/releases/tag/v0.6.0)

bump: rattler 0.6.0

---

pixi.lock
pixi.toml

fix: add perl and extra platforms

---

Cargo.lock
Cargo.toml
src/build.rs
src/console_utils.rs
src/index.rs
src/main.rs
src/packaging.rs
src/render/solver.rs
src/source/mod.rs
src/test.rs
src/windows/link.rs

This still removes some finished progress bars here and there and I have not figured out why yet.

Format tracing

---

src/recipe/stage1.rs
src/recipe/stage2/build.rs

fix: parsing errors and panics

---

src/recipe/error.rs
src/recipe/snapshots/rattler_build__recipe__stage1__tests__package_invalid_fields.snap
src/recipe/snapshots/rattler_build__recipe__stage1__tests__package_missing_fields.snap
src/recipe/stage2.rs
src/recipe/stage2/about.rs
src/recipe/stage2/snapshots/rattler_build__recipe__stage2__about__test__invalid_license.snap
src/recipe/stage2/snapshots/rattler_build__recipe__stage2__about__test__invalid_url.snap
src/recipe/stage2/source.rs

- Improvement to finding the span length when a end span is not provided
- Specialize some errors for nicer error messages

feat(recipe): Improvements to error messages

---

src/recipe/stage2.rs
src/recipe/stage2/build.rs
src/recipe/stage2/requirements.rs

fix(recipe): Fix inline-if parsing dependencies

---

src/recipe/error.rs

I stumbled over this and thought it can be improved readability wise.

Simplify Display impl for ErrorKind

---

examples/curl/recipe.yaml
src/env_vars.rs
src/index.rs
src/macos/link.rs
src/main.rs
src/windows/env.rs

Starting to tackle #255 a little

Unwrap removal

---

src/packaging.rs
src/source/copy_dir.rs
src/source/mod.rs

This is not yet in a ready state. I propose this here initially, so we can talk about the API of the type.
@baszalmstra You also said that this would be a good idea, so pinging you here for a first general review whether this goes into the right direction for you!

Rewrite copy_dir() fn into buildable object

---

src/source/host_git_source.rs

Remove assert, and raise error if git-lfs required by the git source but not installed.

fix: remove assert & handle lack of lfs better

---

src/build.rs
src/main.rs
src/metadata.rs
src/test.rs
src/tool_configuration.rs

feat: Add --no-test CLI option

---

docs/recipe_file.md
src/recipe/parser/source.rs
src/source/host_git_source.rs

Unit tests should already handle it, but should we add a lfs test repo for end-to-end test?
Fixes #285

feat: add lfs option to git source

---

Cargo.lock
Cargo.toml
src/render/resolved_dependencies.rs

This needs one more update in `rattler`, but then we should be good! 
Fixes #266

use latest rattler with secret redaction

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
src/hash.rs
src/lib.rs
src/main.rs
src/metadata.rs
src/recipe.rs
src/recipe/custom_yaml.rs
src/recipe/custom_yaml/rendered.rs
src/recipe/error.rs
src/recipe/parser/build.rs
src/recipe/parser/output.rs
src/recipe/parser/requirements.rs
src/recipe/parser/source.rs
src/render/mod.rs
src/render/pin.rs
src/selectors.rs
src/source/copy_dir.rs
src/source/git_source.rs
src/source/mod.rs
src/source/patch.rs
src/source/url_source.rs
src/test.rs
src/variant_config.rs

Remove some unused code and use `IndexMap` exclusively.

added docs everywhere and refactor some bits

---

src/hash.rs
src/packaging.rs
src/snapshots/rattler_build__metadata__test__read_full_recipe-2.snap
src/snapshots/rattler_build__metadata__test__read_full_recipe.snap
test-data/rendered_recipes/curl_recipe.yaml
test-data/rendered_recipes/rich_recipe.yaml

and store hash_input.json in the package as well

render hash info with all information incl. hash_input

---

src/main.rs

fix: error when output directory in recipe folder

---

src/index.rs
src/metadata.rs
src/source/mod.rs

removed a couple of unwraps and removed some unnecessary operations.

fix: unwraps & cleanup to_string

---

Cargo.lock
Cargo.toml
src/main.rs
src/test.rs
src/tool_configuration.rs

Blocked by https://github.com/mamba-org/rattler/pull/420

Add option and env variable to disable zstd and bz2

---

docs/recipe_file.md

I think we should improve the comments and explanations here in general, any suggestions or guidelines I should follow while doing that?

fix: add docs for package-contents test

---

src/recipe/custom_yaml.rs

fix: improve error messages

---

src/recipe.rs
src/recipe/custom_yaml.rs
src/recipe/custom_yaml/rendered.rs
src/recipe/error.rs
src/recipe/parser.rs
src/recipe/parser/about.rs
src/recipe/parser/build.rs
src/recipe/parser/package.rs
src/recipe/parser/requirements.rs
src/recipe/parser/script.rs
src/recipe/parser/source.rs
src/recipe/parser/test.rs
src/variant_config.rs

re-reviewing. my code, for any bugs (all errs should be followed by a is not empty and report error api).
Might rework, some stuff for better APIs.

fix: rolling errors for render and try convert api

---

src/test.rs

set -x only with bash

---

src/recipe/parser.rs
src/recipe/parser/about.rs
src/recipe/parser/build.rs
src/recipe/parser/package.rs
src/recipe/parser/source.rs
src/recipe/parser/test.rs
src/used_variables.rs

cleans up the api to not require manual if checks for errs.

fix: cleanup code for render and try_convert api

---

Cargo.lock
Cargo.toml
src/source/mod.rs
test-data/recipes/globtest/recipe.yaml

feat: tar & zip in rust

---

src/source/mod.rs

just a minor cleanup for the code.

fix: minor cleanup

---

test-data/recipes/toml/recipe.yaml

this test was failing because of setuptools 69

make toml test more reproducible

---

src/source/mod.rs

More simpler fix for the issue mentioned in #453

fix: create a temporary directory next to target

---

.github/workflows/end-to-end.yml
Cargo.lock
Cargo.toml
src/main.rs
src/upload/anaconda.rs
src/upload/mod.rs
src/upload/package.rs
test/end-to-end/test_simple.py

- add uploading to anaconda.org
- use shared Package struct
- rename to ExtractedPackage
Closes #440

Add support for uploading to anaconda.org

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
rust-tests/src/lib.rs
src/main.rs
src/packaging.rs
test/end-to-end/test_simple.py

TODO: 
- make sure that thread count for zstd compression doesn't alter the result.

upgrade all packages and get rid of git dependency on marked-yaml

---

src/recipe/jinja.rs

Rewrote my older test which had issues, this fixes failing unit-tests.

fix: non deterministic git tests

---

examples/xtensor/recipe.yaml
src/packaging.rs
src/recipe/parser.rs
src/recipe/parser/build.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__binary_relocation.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__binary_relocation_paths.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
test-data/recipes/test-parsing/recipe_build_binary_relocation.yaml
test-data/recipes/test-parsing/recipe_build_binary_relocation_paths.yaml

feat: add `binary_relocation` to the recipe

---

rust-tests/src/lib.rs
src/recipe/parser/source.rs
src/source/url_source.rs
test-data/recipes/correct-sha/recipe.yaml

fix: flush files after download

---

docs/automatic_linting.md
docs/compilers.md
docs/experimental_features.md
docs/highlevel.md
docs/recipe_file.md
docs/variants.md

- fixing minor errors
- improving styling
- and deals with issues I created in the experimental features docs pr

fix: docs and improve stylings

---

Cargo.lock
Cargo.toml
src/build.rs
src/main.rs
src/metadata.rs
src/packaging.rs
src/snapshots/rattler_build__metadata__test__read_full_recipe-2.snap
src/snapshots/rattler_build__metadata__test__read_full_recipe.snap
src/snapshots/rattler_build__metadata__test__read_recipe_with_sources.snap
test-data/rendered_recipes/curl_recipe.yaml
test-data/rendered_recipes/git_source.yaml
test-data/rendered_recipes/rich_recipe.yaml

expose and store compression level and compression threads

---

Cargo.lock
Cargo.toml
src/packaging.rs
test-data/recipes/entry_points/additional_entrypoints.yaml
test/end-to-end/test_simple.py

fix: write out entry points for non-noarch packages

---

docs/recipe_file.md
examples/cmpcdt/recipe.yaml

fix: document jinja functions

---

src/recipe/parser.rs

Now:
Fixes https://github.com/prefix-dev/rattler-build/issues/382

fix: package field error message

---

.github/workflows/docs.yml
mkdocs.yml
pixi.lock
pixi.toml

Sample it at: https://swarnimarun.github.io/rattler-build
Latest(0.7.0): https://swarnimarun.github.io/rattler-build/latest
Dev(master): https://swarnimarun.github.io/rattler-build/dev
This is still draft as I am currently stuck on fixing the CI to actually work with mike which is harder than it looks. 
Also should we setup a gh-pages branch that will reduce the deploy from artifact step. cc: @wolfv 
Note: the current issue with CI setup is getting output to a directory, `mike` the tool mkdocs uses for versioning doesn't support output to a directory, it only supports pushing to a branch.

feat: documentation versioning

---

src/packaging.rs

fix: use the correct default for rpath

---

Cargo.lock
Cargo.toml
src/build.rs

I hope this works well on Windows, too! :)

fix: also filter the stderr of the build process

---

src/build.rs

fix: use expect instead of unwrap

---

src/package_test/run_test.rs

@pavelzw I did some hackery to make the build deps work :)

install build dependencies when running tests

---

src/build.rs
src/packaging.rs
src/recipe/error.rs
src/recipe/parser.rs
src/recipe/parser/build.rs
src/recipe/parser/glob_vec.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_globvec.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_globvec_fail.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/variant_config.rs
test-data/recipes/always-copy-files/recipe.yaml
test-data/recipes/always-include-files/recipe.yaml
test/end-to-end/test_simple.py

cc @orhun you also did some work on glob's recently.
This introduces a new type that renders them as regular strings, but also eagerly parses them so that we can emit errors right away.

add `GlobVec`, `always_copy_files` and `always_include_files`

---

src/linux/link.rs
src/packaging.rs
src/post.rs
src/recipe/parser/build.rs
src/recipe/parser/glob_vec.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap

Move `rpath_allowlist` and `relocate_paths` to `GlobVec`

---

docs/recipe_file.md
examples/rich/recipe.yaml
examples/xtensor/recipe.yaml
src/build.rs
src/package_test/content_test.rs
src/package_test/mod.rs
src/recipe/parser.rs
src/recipe/parser/test.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
test-data/package_content/test_bin_unix.yaml
test-data/package_content/test_bin_win.yaml
test-data/package_content/test_files.yaml
test-data/package_content/test_include_unix.yaml
test-data/package_content/test_include_win.yaml
test-data/package_content/test_lib_linux.yaml
test-data/package_content/test_lib_macos.yaml
test-data/package_content/test_lib_win.yaml
test-data/package_content/test_site_packages_unix.yaml
test-data/package_content/test_site_packages_win.yaml

This is coming together nicely now (I hope). 
@pavelzw maybe you want to have a look.

add many more package content tests and refactor the implementation

---

src/main.rs
src/recipe/custom_yaml.rs
src/recipe/parser/build.rs
test-data/recipes/variant_config/recipe.yaml
test-data/recipes/variant_config/variant_config.yaml
test/end-to-end/test_simple.py

fix using variant jinja in env vars and add tests

---

.github/workflows/rust.yml

testing it out at https://github.com/pavelzw/rattler-build/actions/runs/7724654034/job/21057223260

Fix release binaries

---

src/post_process/relink.rs
src/post_process/snapshots/rattler_build__post_process__python__tests__replace_shebang_in_file-2.snap
src/post_process/snapshots/rattler_build__post_process__python__tests__replace_shebang_in_file.snap
src/recipe/parser/build.rs
src/recipe/parser/glob_vec.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_all_or_globvec-2.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_all_or_globvec-3.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_all_or_globvec.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__binary_relocation.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__binary_relocation_paths.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__complete_recipe.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
test-data/recipes/test-parsing/single_output.yaml
test-data/shebang/replace_shebang_1.py
test-data/shebang/replace_shebang_2.py

Parses the prefix detection section as described in #526. 
Doesn't use the information anywhere (yet)!

implement prefix detection parsing

---

src/main.rs

chore: suppress noisy auth storage warnings

---

src/lib.rs
src/linux/link.rs
src/macos/link.rs
src/packaging.rs
src/packaging/metadata.rs
src/post_process/python.rs
src/recipe/jinja.rs
src/utils.rs

Resolve rpath

---

src/post_process/checks.rs

Take system libs into account while checking links

---

src/post_process/checks.rs

fix: use only DSO packages during overdepending checks

---

src/recipe/parser/output.rs
src/variant_config.rs
test-data/recipes/output_order/order_1.yaml

This section will need a bit of a refactor though :)
Should fix #614 and #553 
Will need to clean things up though

fix buildorder

---

src/upload/package.rs

see https://github.com/mamba-org/rattler/issues/527 and https://discord.com/channels/1082332781146800168/1082338253925003385/1206564460601278504

use VersionWithSource when uploading

---

.github/workflows/rust.yml
Cargo.toml
src/recipe/jinja.rs
src/source/git_source.rs
src/system_tools.rs

Add support for linux-aarch64

---

src/recipe/custom_yaml/rendered.rs
src/recipe/parser.rs
src/recipe/parser/build.rs
src/recipe/parser/skip.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__bad_skip_multi_output.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__bad_skip_single_output.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/used_variables.rs
test-data/recipes/test-parsing/recipe_bad_skip.yaml
test-data/recipes/test-parsing/recipe_bad_skip_multi.yaml
test-data/recipes/test-parsing/xtensor.yaml

This implements the 
```yaml
skip:
- win
- osx and arm64
```
syntax as described in the CEP.

feat: implement skip as list

---

src/render/solver.rs

fixes https://github.com/prefix-dev/rattler-build/issues/639

fix: retain order of channels for proper strict priority handling

---

src/linux/link.rs
src/macos/link.rs
src/windows/link.rs

feat: use mmap for better performance while reading files

---

README.md

Alpine package is pending review: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61403

docs: update the distro packages section in README.md

---

.github/workflows/rust.yml

fix: ensure tagged releases are marked as latest when created

---

src/render/solver.rs

fix: do not use progressbar for JSON output

---

rust-tests/src/lib.rs
src/lib.rs
src/render/resolved_dependencies.rs
src/render/solver.rs
src/tool_configuration.rs

feat: --render-only will make a dry-run and will not install resolved packages

---

src/lib.rs
src/main.rs

feat: make --render-only output more parsing friendly

---

src/recipe/parser/test.rs

chore: use correct error message for expected fields

---

src/packaging.rs

feat: add license warnings to warnings summary

---

src/packaging.rs

fix: fail build when no license files are found

---

.github/workflows/docs.yml
pixi.lock
pixi.toml

same as https://github.com/prefix-dev/pixi/pull/1074

fix: docs CI

---

src/packaging.rs

just a quickie, couldn't resist.
closes #775

chore: sort info files to bottom

---

examples/xtensor/recipe.yaml
src/source/mod.rs
src/source/patch.rs

feat: improve error messages when patching

---

src/source/patch.rs

fix: ignore `/dev/null` when guessing strip level

---

src/recipe/parser/requirements.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__requirements__test__pin_package.snap

This makes the requirements serialization a bit more ✨ 

---

src/script.rs

feat: better help when script fails

---

src/used_variables.rs

fix: we are using `if` expressions, not statements

---

Cargo.lock
Cargo.toml
src/windows/env.rs

fix: remove todo about cygwin path and add remaining windows env vars

---

src/env_vars.rs

fix: do not modify cxxflags

---

.github/workflows/rust.yml

based on suggestions from: 
https://github.com/johnthagen/min-sized-rust
https://arusahni.net/blog/2020/03/optimizing-rust-binary-size.html
and pixi workflow

feat: make binary smaller size

---

docs/recipe_file.md
src/render/resolved_dependencies.rs

corrections to docs and GHA summary

---

src/render/solver.rs
test-data/recipes/post-link/recipe.yaml
test/end-to-end/test_simple.py

Fixes https://github.com/prefix-dev/rattler-build/issues/185

fix: enable post-link script execution

---

pixi.lock
pixi.toml

Getting my contributions up for this project ;)

chore: update pixi project

---

examples/linking/recipe.yaml

Should fix: https://github.com/prefix-dev/rattler-build/issues/880

fix: fix test for zlink for macos

---

.github/workflows/end-to-end.yml
pixi.lock
pixi.toml
test/end-to-end/__snapshots__/test_simple/test_filter_files.json
test/end-to-end/__snapshots__/test_simple/test_git_submodule.json
test/end-to-end/__snapshots__/test_simple/test_include_files.json
test/end-to-end/__snapshots__/test_simple/test_post_link.json
test/end-to-end/__snapshots__/test_simple/test_symlink_recipe.json
test/end-to-end/test_simple.py

We can remove a bunch of annoying code with `syrupy` :)

Python snapshot tests for end-to-end testing

---

examples/bitfurnace/README.md
examples/bitfurnace/recipe.yaml
examples/bitfurnace/xtensor.yaml

just a little example, maybe someone is interested in reviving this idea :)

bitfurnace examples

---

src/source/extract.rs
src/source/mod.rs
src/source/url_source.rs

This will speed up locally building quite a lot and enable some other features down the line (such as diffing between the work dir and the source code, to create patches easily).

Extract tar- and zip immediately and use copydir from cache

---

docs/reference/jinja.md
docs/reference/recipe_file.md
src/recipe/jinja.rs

cc @jaimergp what do you think?

feat: change `env` implementation

---

docs/special_files.md

Reflects what's been discussed here: https://github.com/prefix-dev/rattler-build/issues/185.

Update docs for special scripts to reflect changes in v0.17.

---

src/recipe/jinja.rs

This is the same behavior as `conda-build` has, apparently.

fix: use language as default compiler name

---

Cargo.lock
Cargo.toml
docs/special_files.md
src/build.rs
src/console_utils.rs
src/lib.rs
src/package_test/run_test.rs
test-data/recipes/downstream_test/fail.yaml
test-data/recipes/downstream_test/fail_prelim.yaml
test-data/recipes/downstream_test/succeed.yaml
test/end-to-end/test_simple.py

first pass at implementing the downstream test execution.

feat: implement downstream test

---

src/cache.rs
src/packaging.rs
src/packaging/file_finder.rs
src/packaging/metadata.rs

This makes the cache work properly for multiple outputs :)

feat: replace the prefix in cached files

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
src/recipe/custom_yaml.rs

chore: prepare release 0.18.1

---

examples/xtensor/build.nu
src/recipe_generator/cran.rs
src/recipe_generator/mod.rs
src/recipe_generator/pypi.rs

- A build-string in R packages is replaced by just a number (e.g. 3.4-5 becomes 3.4.5)
- I added a few more licenses
- A better list of all the builtins
- Only the first URL is inserted as Homepage
cc @roaldarbol

feat: improvements to the R generator

---

src/recipe/parser/build.rs
src/recipe/parser/package.rs

This PR exposes fields we need to build directly with: https://github.com/prefix-dev/pixi-build

feat: expose fields needed for building an output directly

---

src/main.rs
src/opt.rs

fix: fix typo of feature recipe-generation

---

docs/authentication_and_upload.md

doc: typo of BasicHTTP result in json decode error

---

docs/reference/recipe_file.md

I found the original docs of `conda-build` more insightful, so I extended the `rattler-build` docs in a similar manner

docs: Clarify section on `run_exports`

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
src/render/solver.rs

bumping rattler to benefit from larger zip file support!

chore: prepare release 0.21.0

---

src/recipe/custom_yaml.rs

feat: disallow dash in version

---

src/cache.rs

for #1054 
Not sure yet what the root cause is, though.

add a debug message when prefixes are not matching

---

src/cache.rs
src/render/resolved_dependencies.rs
test-data/recipes/cache/recipe-cmake.yaml
test/end-to-end/test_simple.py

This fixes the issue where cmake is not found in the cache. Need to figure out how to add a useful test here.

Install cache packages

---

src/script.rs

cc @h-vetinari this might help! :)

add @echo on

---

src/package_test/serialize_test.rs
src/script.rs
test-data/recipes/test-execution/recipe-test-succeed.yaml
test/end-to-end/__snapshots__/test_simple.ambr

This is not yet implementing the real _delayed_ rendering & evaluation because that would need a slightly larger refactor. But it implements some lightweight rendering with values from the context etc.

fix: re-enable rendering in test script section

---

src/console_utils.rs
src/main.rs
src/opt.rs
src/script.rs
src/source/extract.rs

cc @h-vetinari this should stop wrapping lines in CI :)
fixes #1124

fix: some regressions with pretty-printing and add no-wrap printing

---

docs/reference/recipe_file.md

learned about this [here](https://github.com/conda-forge/suitesparse-feedstock/pull/98#discussion_r1860019072), and it's super useful for multi-platform multi-output recipes!

[doc] mention automatic file extension in output/build/script

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
src/package_test/run_test.rs
test-data/recipes/test-execution/recipe-test-succeed.yaml

@tobias-fischer this is the fix for the test failures. Sorry!

use the correct prefix for `os_vars` in test

---

src/cache.rs
test-data/recipes/cache/recipe-compiler.yaml
test-data/recipes/prefix_detection/create_files_with_prefix.py
test/end-to-end/test_simple.py

This should fix the #1290 issue.

clean prefix, and restore pristine cache state

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
src/recipe/parser/requirements.rs
src/recipe_generator/pypi.rs

Turns out we don't need to do any heavy parsing ourselves as we can just use the PyPI API :)

feat: remove rip and use pypi json API instead

---

docs/reference/cli.md

- don't display hidden flags
- don't display values of boolean flags
Depends on https://github.com/ruben-arts/clap-markdown/pull/1

docs: improve CLI reference

---

Cargo.toml
src/upload/mod.rs
src/upload/trusted_publishing.rs

Add retry logic to upload functions

---

src/recipe/parser/output.rs
src/variant_config.rs

fixes https://github.com/conda-forge/conda-smithy/pull/2207#event-15831388488

fix: allow schema version toplevel

---

docs/reference/cli.md
src/opt.rs

docs: hide deprecated `--no-test`

---

Cargo.lock
Cargo.toml
src/upload/mod.rs

Unfortunately normal ReqwestWithMiddleware doesn't work because the request is not cloneable as we are attaching a file stream

fix: upload with retry

---

src/render/resolved_dependencies.rs

simplify and improve error message when parsing spec from variant

---

src/packaging.rs

This should help when a user tries to run multiple rattler-build processes in parallel. It should also help to clean up half-written archives and similar problems.

feat: write package to temporary file, then persist to final name

---

docs/reference/cli.md
docs/reference/python_bindings.md
mkdocs.yml
pixi.lock
pixi.toml
py-rattler-build/rattler_build/__init__.py

- Auto-generate docs
- Extend existing docs

docs: Python bindings

---

docs/reference/python_bindings.md
mkdocs.yml
pixi.lock
pixi.toml

docs: improve python binding docs

---

docs/reference/python_bindings.md
mkdocs.yml
py-rattler-build/rattler_build/__init__.py

docs: Add parameter table for each function

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
test/end-to-end/test_simple.py

This fixes an important issue with `track_features`.

chore: update all the dependencies

---

py-rattler-build/src/lib.rs
src/opt.rs
src/upload/anaconda.rs
src/upload/conda_forge.rs
src/upload/mod.rs
src/upload/prefix.rs

Do not merge as support hasn't been rolled out on prefix.dev :)

feat: use multipart/form and allow uploading attestations

---

pixi.lock
pixi.toml

Otherwise we hit a bug, where copy-pasting a snippet adds an additional newline after every line

docs: update mkdocs dependencies

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
py-rattler-build/Cargo.toml
rust-tests/Cargo.toml
tbump.toml

Also bump rattler and everything else.

chore: release 0.36.0

---

src/recipe/parser/requirements.rs
src/render/resolved_dependencies.rs
test-data/recipes/run_exports/multi_run_exports_dict.yaml
test-data/recipes/run_exports/multi_run_exports_list.yaml
test/end-to-end/__snapshots__/test_simple/test_run_exports.json
test/end-to-end/test_simple.py

Fixes: https://github.com/prefix-dev/rattler-build/issues/1468
Fixes: https://github.com/prefix-dev/rattler-build/issues/1305

fix: run exports parsing

---

docs/build_options.md

#598 added these features but did not add them to the documentation.

Document prefix patching options

---

src/render/resolved_dependencies.rs

Resolves #1486
I don't really know Rust, so there might be a better way to do this, but it works on my machine :)

feat: add output name to finalized run dependencies

---

src/package_test/content_test.rs

feat: emscripten build outputs will be produced with .js and .wasm extensions

---

src/lib.rs
src/metadata.rs
src/render/pin.rs

cc @pavelzw does that fix your pin_subpackage issue?

fix: more `VersionWithSource` in additional places

---

docs/config.md
docs/reference/cli.md
mkdocs.yml
src/lib.rs
src/main.rs
src/opt.rs
src/tool_configuration.rs

follow-up of https://github.com/prefix-dev/rattler-build/pull/1563
closes #717, closes #834
xref https://github.com/conda-forge/conda-smithy/pull/2309, xref https://github.com/conda-forge/conda-smithy/pull/2226

feat: Add s3 and mirror configuration from pixi config

---

docs/reference/recipe_file.md

Add example of setting the python version during testing.

Update python test docs

---

docs/variants.md
py-rattler-build/src/lib.rs
src/lib.rs
src/opt.rs
src/variant_render.rs
test-data/recipes/channel_sources/conda_build_config.yaml
test-data/recipes/channel_sources/recipe.yaml
test/end-to-end/test_simple.py

follow-up of #1416 
closes https://github.com/conda-forge/conda-smithy/issues/2226
cc @mgorny

feat: Read channel_sources from variant file

---

Cargo.toml
benches/parse_file.rs
src/lib.rs
src/metadata.rs
src/recipe/jinja.rs
src/selectors.rs
test-data/recipes/relative_file_loading/data/package_data.yaml
test-data/recipes/relative_file_loading/recipe.yaml
test/end-to-end/test_simple.py

feat: Add support for loading files relative to recipe path

---

src/render/solver.rs

Fixes https://github.com/prefix-dev/rattler-build/issues/1439

fix: make conda recognize rattler-build environments

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
src/source/patch.rs

Instead of trying to properly parse the patch files, we just parse what we need for now.

fix: patch parsing fixes

---

docs/converting_from_conda_build.md

I had to use Discord search to figure out the name of this awesome tool. I think it belongs here in the rattler-build docs as well!

docs: mention `feedrattler`

---

src/utils.rs

fix: try to make test less flaky

---

src/source/copy_dir.rs

Fix file permissions when using multiple output cache

---

src/source/git_source.rs

Help debug https://github.com/conda-forge/katago-feedstock/pull/17

feat: log git errors

---

src/source/git_source.rs

@hadim you could also try this binary once it's finished.

fix: win git rev

---

docs/reference/cli.md
docs/selectors.md

https://discord.com/channels/1082332781146800168/1082338253925003385/1386799691815190701

docs: alternatives to selectors for scalar fields

---

src/source/create_patch.rs
test/end-to-end/test_create_patch.py

refactor: improve patch creation logging and ensure colored diff output

---

.github/workflows/rust.yml
Cargo.toml
pixi.toml
src/source/patch.rs

i also added a new command to test on locally with pixi, hopefully that was the correct choice

feat: add support for patch-test-extra feature in tests and configuration

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
py-rattler-build/Cargo.toml
src/metadata.rs
src/packaging/metadata.rs

This unblocks https://github.com/prefix-dev/pixi/pull/4036/files

feat: bump rattler to latest

---

src/packaging/metadata.rs
test/end-to-end/__snapshots__/test_simple/test_symlink_recipe.json
test/end-to-end/__snapshots__/test_symlinks/test_symlink_cache.json
test/end-to-end/test_symlinks.py

fix: include symlink even outside

---

docs/multiple_output_cache.md
docs/reference/cli.md
docs/reference/recipe_file.md
docs/variants.md
pixi.lock
pixi.toml

- improve variants docs
- fix broken anchors
- upgrade mkdocs dependencies

docs: improve variants docs and fix warnings

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
py-rattler-build/Cargo.toml
src/lib.rs
src/metadata.rs
tbump.toml

Waiting for a rattler release so that main will be green as well :)

chore: prepare release 0.48.0

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
py-rattler-build/Cargo.toml
tbump.toml

Fixes an issue with virtual packages.

chore: release 0.48.1
