.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/rust-compile.yml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/prefix-dev/rattler-build/actions/runs/4725432487:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …

Replace unmaintained actions-rs/* actions in CI workflows

---

Cargo.lock
src/packaging.rs

Files need to be moved from `bin/` or `Scripts` into the special `python-scripts` folder.
This code doesn't compile yet, I'll fix it tomorrow :)

wip fix to add noarch bin files to python-scripts

---

src/source/mod.rs
src/source/url_source.rs

Allow to specify a local file as source:
```yaml
source:
- url: file:///build/rich/rich-{{ version }}.tar.gz
sha256: fb9d6c0a0f643c99eed3875b5377a184132ba9be4d61516a55273d3554d75a39
```
Fix #176
I never wrote any rust before, so this might require some change :-)

Add support for local source file url scheme

---

src/render/solver.rs

Pretty useless functionally but still manual implementation of a transpose, is redundant. Hope no one minds this. `:P`

fix: minor code nit

---

src/build.rs
src/main.rs
src/metadata.rs
src/packaging.rs

Add a new command line option to build a `.conda` package straight away instead of a `.tar.bz2`.
Fix #170

feat: build .conda package right away

---

Cargo.lock
Cargo.toml
src/source/mod.rs

Patches for #174
* One cleanup for the patch from #174 itself
* Removal of the usage of `ignore::gitignore`, replaced by `glob` crate machinery
* Refactoring for a bit more streamlined code.
@wolfv please have a look.

Copy dir without ignore gitignore

---

.github/workflows/rust-compile.yml

Change the GH action to use `dtolnay/rust-toolchain` (which is used anyways) to install the `rustfmt` component, hopefully showing off a few seconds of the overall duration of the job.

Fix: Use dtolnay/rust-toolchain to install rustfmt component

---

src/source/mod.rs

This patch makes the `copy_dir()` function return the pathes it copied (targets, not sources).
This is needed so the fn is more useful when using it to rewrite copy functionality later.

Make copy_dir() return copied pathes

---

src/packaging.rs
src/source/mod.rs

Closes #207 
Does the error message look good to you?

Add more explanatory error message when not copying license files

---

src/packaging.rs
src/recipe/stage2/source.rs
src/source/mod.rs
src/test.rs
test-data/recipes/test_files/recipe.yaml

This adds a `file_name` field to URL source (different from `fn` in conda's meta.yaml).
I also had to modify copy_dir a bit to not delete the existing files in the target directory.
During the work on this, I also discovered that we are currently hard coding a `bash` invocation to execute the tests. While that works great on Unix, I think we need to make some additional adjustments for Windows and rewrite that part a little bit.

feat: implement test file copying with copy dir and improve url source

---

src/recipe/custom_yaml.rs
src/recipe/custom_yaml/rendered.rs
src/recipe/parser/about.rs
src/recipe/parser/build.rs
src/recipe/parser/package.rs
src/recipe/parser/source.rs
src/variant_config.rs

This also allowed me to find a bug where in a particular case rendering YAML sequences should render as a null node but was resulting in an empty `Vec`.

feat(recipe): Expand `TryConvertNode` implementations to include `Option`

---

README.md

I added a homebrew formula for rattler-build to my private tap. Will merge into homebrew-core once this repo hits 100 stars.
https://github.com/pavelzw/homebrew-pavelzw/pull/125
Formula at https://github.com/pavelzw/homebrew-pavelzw/blob/main/Formula/rattler-build.rb
Since this formula doesn't provide pre-built bottles, the installation via homebrew takes ~1.5min

Add reference to installation via homebrew

---

src/recipe/jinja.rs
src/used_variables.rs

TODO:
Notes:
- Discuss the approach to providing config into the set_jinja function. (currently we can't avoid clone, there are ways around it but would need some rearchitecturing)
- Made changes to a couple places where the unwrap was quite unbearable for my OCD(unwrapping while parsing doesn't seem nice).
- Figure out how to add end to end tests.
Fixes #91

feat: add cdt function

---

src/env_vars.rs

Note: we use a configured timestamp. The spec says we should find the latest modification time of the source code but I am not sure if that's really useful.
For purposes of rebuilding we would just re-use the timestamp from the original package.
https://reproducible-builds.org/specs/source-date-epoch/

Source date epoch

---

src/main.rs
src/metadata.rs

Adds build option akin to conda with `--no-build-id`. 
Tasks:
Notes:
- Discuss, if we should provide an ENV variable as well to setup the flag?
- Figure out, how to add tests for the newly added option.
Fixes #248

feat: no-build-id aka static build dirs

---

src/source/mod.rs

Shouldn't be needed, git_src returns a SourceError as well. This should be removed in a bit by my another PR. But until then.

fix: manual try expr implementation

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
rust-tests/src/lib.rs

use command `cargo t -p rust-tests` to run the end to end tests
TODO:

feat: add tests in rust

---

.github/workflows/rust-compile.yml

It seems that when cross is activated, a very old (1.0) openssl version is linked which isn't available on modern systems.

Don't use cross for x86_64-unknown-linux-gnu

---

src/render/resolved_dependencies.rs
src/render/snapshots/rattler_build__render__resolved_dependencies__tests__dependency_info_render.snap
src/snapshots/rattler_build__metadata__test__read_full_recipe-2.snap
src/snapshots/rattler_build__metadata__test__read_full_recipe.snap
src/snapshots/rattler_build__metadata__test__resolved_dependencies_rendering.snap
test-data/rendered_recipes/curl_recipe.yaml
test-data/rendered_recipes/dependencies.yaml
test-data/rendered_recipes/rich_recipe.yaml

I want to get rid of the YAML tagging. 
Currently this renders as `!Raw`, `!Compiler`, etc.

Improve rendering of DependencyInfo

---

docs/recipe_file.md

Explains using the new jinja string interp syntax for `recipe.yaml` as described in https://github.com/conda-incubator/ceps/pull/54

Fix jinja string interp instructions

---

rust-tests/src/lib.rs
src/linux/link.rs
src/main.rs
src/metadata.rs
src/packaging.rs
src/rebuild.rs
src/recipe/jinja.rs
src/recipe/parser/output.rs
src/render/resolved_dependencies.rs
src/render/solver.rs
src/test.rs
src/windows/link.rs

4 of the unwraps are now expected as they can't be fixed trivially, i.e. require major refactoring and are unreachable(to my knowledge) and tests have been untouched.
Fixes https://github.com/prefix-dev/rattler-build/issues/255

fix: remove all the unwraps from production code

---

src/main.rs
src/recipe/error.rs
src/recipe/parser.rs
src/recipe/parser/about.rs
src/recipe/parser/output.rs
src/recipe/parser/package.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__about__test__invalid_license.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__about__test__invalid_url.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__output__tests__recipe_schema_error-3.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__package__tests__invalid_fields.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__package__tests__missing_fields.snap
src/recipe/snapshots/rattler_build__recipe__error__tests__miette_output.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__context_not_mapping.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__context_value_not_scalar.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__jinja_error.snap
src/used_variables.rs
src/variant_config.rs

We now show most of the errors other than yaml parsing itself at once.

feat: error collect as vec

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
pixi.toml

In the 0.6.1 release, you forgot to update the version. This makes sure that this won't happen again.

Add version assertion for release

---

src/source/mod.rs
src/source/url_source.rs

Zips don't need to have a root file, unlike normal tar even if they can be unzipped from tar extractor. So unconditional strip components for zip files it will break "most but not all" zip files. :3
Fixes #316

fix: ensure zips without root are handled

---

Cargo.lock
Cargo.toml
docs/cli_usage.md
mkdocs.yml
rust-tests/src/lib.rs
src/main.rs

uses clap-complete should support most shells, for support for any other shell an issue would need to be filed to clap
Fixes #366

feat: add completions generation for shells

---

src/main.rs
src/upload.rs

This also includes a small change to the upload CLI interface, as `package_name` is now a mandatory field and no longer an option.

feat: artifactory upload

---

src/packaging.rs

TODO:
Note: no utf-16 handling as technically all files can be utf-16 or utf-32 even on linux, and further based on platform we would have to handle le and be(endianness) spec as well. Hence it's better to handle these as binary or a different format all together.
fixes #369

fix: handling both forward and backward slash

---

docs/cli_usage.md
src/packaging.rs
test-data/recipes/toml/expected/index.json

Fix https://github.com/prefix-dev/rattler-build/issues/211
It does not seem much more complicated than that.

Fix deduplication issue in create_index_json function

---

rust-tests/src/lib.rs
src/source/mod.rs
test-data/recipes/zip-source/recipe.yaml

Closes #446.
We now first extract the zip/tar files into a tempdir and then move all files to the target directory, deleting the root_dir if one exists.

fix extraction for zip files

---

docs/cli_usage.md
src/main.rs

fix: improve completions dx

---

src/main.rs

Should now be consistent with pixi, for the cli part.
note:
Also the issue regarding broken formatting in completions is due to a bug in the completions generated we will have to manually replace parts of the completion like pixi does. cc: @pavelzw

fix: use env for shell detection

---

src/main.rs

https://github.com/prefix-dev/rattler-build/pull/451#issuecomment-1873966597
another thing i noticed that is odd about the shell completion is
```
eval "$(rattler-build completion)"
rattler-build upload prefix --api<TAB>
```
doesn't complete but should complete imo to 
```
rattler-build upload prefix --api-key
```
But this is probably a clap issue.

Improve upload help descriptions

---

docs/index.md
docs/recipe_file.md
docs/testing.md
examples/rich/recipe.yaml
examples/xtensor/recipe.yaml
mkdocs.yml
rust-tests/src/lib.rs
src/build.rs
src/lib.rs
src/main.rs
src/package_test.rs
src/packaging.rs
src/recipe/parser.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__test__test__parsing.snap
src/recipe/parser/test.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/snapshots/rattler_build__metadata__test__read_full_recipe.snap
src/source/copy_dir.rs
test-data/recipes/flask/recipe.yaml
test-data/recipes/package-content-tests/llama-recipe.yaml
test-data/recipes/package-content-tests/recipe-test-fail.yaml
test-data/recipes/package-content-tests/recipe-test-succeed.yaml
test-data/recipes/package-content-tests/rich-recipe.yaml
test-data/recipes/test-execution/recipe-test-fail.yaml
test-data/recipes/test-execution/recipe-test-succeed.yaml
test-data/recipes/test-sources/recipe.yaml
test-data/rendered_recipes/rich_recipe.yaml

```yaml
requirements:
build:
- if: build_platform == linux-64
then:
- arm-emulator
```

[🚧] new multi tests

---

src/render/resolved_dependencies.rs

- This PR uses `ignore_run_export` while building finalized run dependencies.
Closes https://github.com/prefix-dev/rattler-build/issues/113
Note:
`ignore_run_exports_from` is already implementated,
https://github.com/prefix-dev/rattler-build/blob/3e883a6d4d99484ee698ab57cea2e42aebbdecf1/src/render/resolved_dependencies.rs#L481-L487

fix: use ignore_run_exports for building env

---

rust-tests/src/lib.rs
src/render/resolved_dependencies.rs
test-data/recipes/run_exports_from/recipe.yaml

This fixes the issue of ignore_run_exports from_package being ignored for host_env.
And adds test for both cases.

fix: bug with ignore_run_exports_from in host_env & add tests

---

README.md

`rattler-build` can be installed with `pacman` now!

docs: mention the Arch Linux package

---

README.md
docs/index.md

Depends on https://github.com/Homebrew/homebrew-core/pull/159416

Install rattler-build from homebrew-core

---

Cargo.lock
src/render/solver.rs

Fixes this issue while working with the latest revision of `rattler`:
```
thread 'main' panicked at /home/orhun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/drop_bomb-0.1.5/src/lib.rs:113:13:
did not call post_process on InstallDriver / ClobberRegistry
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

feat: perform post processing after package installation

---

src/recipe/custom_yaml.rs
src/recipe/custom_yaml/rendered.rs
test-data/recipes/variant_config/recipe.yaml

This is an extension to the fix for the `env` mapping and skips over any `Null` values in `RenderedMapppings`. 
That means, keys are ignored if the value is `Null`. I do think that's the desired behavior and means we can write stuff like 
```yaml
build:
number: ${{ 10 if false }}
```
without error.

skip over any Null values in mappings

---

docs/index.md

It currently goes to https://prefix-dev.github.io/rattler-build/latest/examples/ which 404s

Fix link to examples

---

docs/recipe_file.md

Pretty sure these are meant to be referring to rattler-build and not boa 😄

Fix references to boa in docs

---

README.md
docs/index.md

I'm wondering whether we should symlink `index.md` and `README.md`...

docs: Add github action to documentation

---

.github/workflows/rust.yml

this might be a short term solution - not tested but I'm positive that it will work

feat: mark version as non-draft after release CI completes

---

.github/workflows/end-to-end.yml
Cargo.lock
Cargo.toml
docs/cli_usage.md
pixi.toml
rust-tests/src/lib.rs
src/build.rs
src/console_utils.rs
src/lib.rs
src/macos/link.rs
src/main.rs
src/metadata.rs
src/package_test/content_test.rs
src/package_test/run_test.rs
src/packaging.rs
src/post_process/checks.rs
src/render/resolved_dependencies.rs
src/render/solver.rs
src/script.rs
src/source/git_source.rs
src/source/mod.rs
src/source/url_source.rs
src/tool_configuration.rs

TODO:
Still needs fixing:
- Add a Github subscriber that prints warning as `::warning::{message}` and error as `::error::{message}`
- Make the summary have proper tables

feat: experimental indent when logging to terminal

---

src/env_vars.rs
src/metadata.rs
src/post_process/python.rs
test-data/recipes/flask/recipe.yaml

This searches for the Python version in the resolved dependencies and adds it.
Should we do the same for `numpy` and `R`?
Fixes #557

always add python version as `$PY_VER`

---

README.md
docs/automatic_linting.md
docs/available_jinja.md
docs/build_options.md
docs/build_script.md
docs/cli_usage.md
docs/compilers.md
docs/experimental_features.md
docs/highlevel.md
docs/index.md
docs/internals.md
docs/package_spec.md
docs/rebuild.md
docs/recipe_file.md
docs/selectors.md
docs/special_files.md
docs/testing.md
docs/tutorials/cpp.md
docs/tutorials/python.md
docs/tutorials/rust.md
docs/variants.md
mkdocs.yml

My initial intention was to only read through/edit the [Advanced Build Options](https://prefix-dev.github.io/rattler-build/dev/build_options/) section but then I ended up reading through and editing all of the docs pages. 😆 
Please feel free to take or leave some of the more minor edits. However, there are some questions that popped up in regards to wording/clarification, which I will point out via comments to this PR.
Thank you to the folks at prefix.dev and other `rattler-build` contributors for providing such detailed and helpful documentation with so many examples! 👍 👍

docs: miscellaneous edits throughout for style and wording

---

docs/recipe_file.md

Add docs to show what to do when a proprietary license wants to be used.

docs: added LicenseRef option

---

src/recipe/parser.rs
src/recipe/parser/source.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__complete_recipe.snap
src/render/solver.rs
src/source/checksum.rs
src/source/extract.rs
src/source/mod.rs
src/source/url_source.rs
test-data/recipes/test-parsing/single_output.yaml
test-data/recipes/test-sources/recipe.yaml

The extraction bars were iterating "too much" because the reader wrapper was in the wrong place. This fixes that.
Also I've implemented checksum handling for local paths. 
I am still wondering if we should make the checksums for URL sources optional.
fixes https://github.com/prefix-dev/rattler-build/issues/560

fix: extraction bars proper length and add checksum verification to path source

---

.github/workflows/rust.yml

we should also set https://github.com/prefix-dev/rattler-build/releases/tag/v0.12.0 as latest :bear:

fix: set release as latest after CI succeeds

---

src/recipe/parser/snapshots/rattler_build__recipe__parser__source__tests__ssh_serialization.snap
src/recipe/parser/source.rs
src/source/git_source.rs
test-data/recipes/git_source/recipe.yaml
test-data/recipes/llamacpp/recipe.yaml

We now support:
```yml
source:
git: git@github.com:killercup/cargo-edit.git
```
Todo list:
closes #672

feat: support scp-style SSH urls for Git source

---

docs/authentication_and_upload.md

Without `export` it doesn't work as the shell variables are not passed to the subprocess.

docs: Use export for shell variables

---

README.md

Adds this badge: [![Pixi Badge](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/prefix-dev/pixi/main/assets/badge/v0.json)](https://pixi.sh)

chore: add pixi badge to the readme

---

src/packaging.rs
src/post_process/relink.rs
src/system_tools.rs

a step towards #699
```sh
× error Error building package: failed to find `patchelf` (cannot find binary path)
Error:   × failed to find `patchelf` (cannot find binary path)
```
I created a new error type because having a new variant in `RelinkError` felt a bit out of place.

chore: log the name of the missing system tool

---

docs/cli_usage.md

Because we don't have any emojis in cli_usage.md, I think it would be nicer to keep the same tone across entire .md
Also FPATH is replaced with PATH

misc: update cli_usage.md

---

.gitignore

I realized `pixi run build-docs` creates the `site/` directory and it shouldn't be committed :bear:

chore: add site directory to .gitignore

---

docs/highlevel.md
src/lib.rs
src/main.rs
src/opt.rs
src/tui/event.rs
src/tui/mod.rs
src/tui/state.rs

This PR adds support for building multiple recipes.
1. You can provide `--recipe` argument multiple times.
```sh
$ rattler-build build -r examples/linking -r examples/mamba
```
This will build the packages in the given order.
2. You can build all the recipes in a directory with using `--recipe-dir` argument.
```sh
$ git clone https://github.com/wolfv/rust-forge
$ rattler-build build --recipe-dir rust-forge/
```
3. TUI is also supported:

feat: support building multiple recipes

---

src/snapshots/rattler_build__variant_config__tests__python_is_not_used_as_variant_when_noarch.snap
src/variant_config.rs
test-data/recipes/variants/boltons_recipe.yaml
test-data/recipes/variants/python_variant.yaml

When having noarch: python in recipe 
```
requirements:
host:
- python
- pip
- setuptools
run:
- pip
```
and also variants.yaml 
```
python:
- 3.8.* *_cpython
- 3.9.* *_cpython
python_impl:
- cpython
- cpython
numpy:
- 1.22
- 1.22
```
rattler-build should render only one recipe and don't take into account python variants ( like how conda render do )

fix: do not take python variant when noarch:python

---

src/lib.rs
src/main.rs
src/tui/mod.rs
src/utils.rs

closes #734
This is not a bulletproof implementation but it does the job:
```sh
cat examples/cargo-edit/recipe.yaml | rattler-build build --render-only
```
Couple of things:
- We heavily depend on recipe path during our build process and it is also required for the _reload_ functionality in TUI - that's why I decided to create a temp dir along with a `recipe.yaml` when stdin is used.
- In the cases where the build requires more than `recipe.yaml` this will fail. But that's fine because it is intended to pass only one file through stdin.
Either way, I think it is a neat feature! Let me know what you think.

feat: support reading recipe from stdin

---

src/snapshots/rattler_build__variant_config__tests__flatten_selectors-2.snap
src/snapshots/rattler_build__variant_config__tests__flatten_selectors.snap
src/snapshots/rattler_build__variant_config__tests__load_config.snap
src/snapshots/rattler_build__variant_config__tests__load_config_and_find_variants.snap
src/utils.rs
src/variant_config.rs
test-data/recipes/variants/recipe.yaml
test-data/recipes/variants/variant_config.yaml

when having in `recipe` requirements:
`-r-base`
and in `variant_config` 
```
r_base:
"4.2"
```
it will not be take into consideration as variant.
In  [ conda_build_config ](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L812)
they store it as underscore so my idea is to check both r_base and r-base if it's in used vars

fix: take into consideration non-canonical variant also

---

src/recipe/error.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__about__test__invalid_license.snap

```
Error:   × Parsing: failed to parse SPDX license: invalid character(s)
│ See <https://spdx.org/licenses> for the list of valid licenses.
│ Use 'LicenseRef-<MyLicense>' if you are using a custom license.
```
closes #675

style: improve spdx license error

---

src/source/git_source.rs

closes #686
Now we check if `git-lfs` is installed via running `git lfs ls-files` command. Also, we checkout a specific Git revision via `git lfs fetch`. `pull` is not required anymore so it is replaced with `checkout`.
> - `git lfs fetch` downloads objects to `.git/lfs/objects`
> - `git lfs checkout` replaces objects in your working directory from `.git/lfs/objects`. Does _not_ download anything.
> - `git lfs pull` is a combination of `git lfs fetch` and `git lfs checkout`

feat: improve git-lfs handling

---

.pre-commit-config.yaml
src/source/mod.rs
test-data/recipes/git_source_patch/patch/ros-humble-ament-package.patch
test-data/recipes/git_source_patch/recipe.yaml
test/end-to-end/test_simple.py

If the `target_directory` is set, we should use that as the cwd to apply patches.

fix: apply patches in target_directory

---

src/lib.rs
src/recipe/jinja.rs
src/recipe/parser.rs
src/selectors.rs
src/variant_config.rs
test-data/recipes/noarch_variant/recipe.yaml
test/end-to-end/test_simple.py

fix: make noarch-unix and noarch-win work

---

src/source/extract.rs
src/source/mod.rs

This is an initial proposal how to fix #821 with relatively low effort.
Maybe a better idea would be to somehow avoid duplicating strings between this new `is_tarball` function and `ext_to_compression`, but I don't have enough Rust knowledge, and I am completely new to rattler codebase.

fix: correctly identify tarballs (#821)

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
src/post_process/python.rs
src/recipe_generator/mod.rs
src/recipe_generator/pypi.rs
src/render/solver.rs
src/script.rs

Unfortunately the latest `reqwest` release means that I had to turn off our pip recipe generation for a moment. Will check for the best way to enable it again.

chore: update dependencies & rattler

---

src/post_process/relink.rs
src/system_tools.rs

This should fix issues with cross-compiling e.g. from linux-64 to osx-arm64 (where we need to invoke `codesign`). A `codesign` is installed in the `$BUILD_PREFIX` and we should preferably use that.

feat: use system-tools from build prefix if they are available

---

docs/authentication_and_upload.md

Attempts to clarify a point that caused me some confusion: The rattler-build docs use "owner" for what conda docs call a "channel" (see [1]) and "channel" for what Anaconda.org docs call a "label" (see [2]). Because of that, I didn't read carefully and assumed "channel" referred to my user/org name on Anaconda.org.
[1] https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/channels.html
[2] https://docs.anaconda.com/free/anacondaorg/user-guide/work-with-labels/

Attempts to clarify docs for Anaconda.org upload

---

docs/internals.md
src/packaging/file_mapper.rs
test-data/recipes/filter_files/recipe.yaml
test/end-to-end/test_simple.py

conda-build filters a few more files before packaging. We're aligning with that. Includes:
- .DS_Store files
- *.la files
- .git* files (incl. .git directories)
https://github.com/conda/conda-build/blob/5f5eebe54b577cc4d9a5fd3f2d0f6516265c2923/conda_build/utils.py#L1572-L1580

fix: filter files like conda-build does

---

examples/cargo-edit/recipe.yaml
examples/rich/recipe.yaml
src/packaging/metadata.rs
src/recipe/parser/source.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/source/mod.rs
src/source/url_source.rs
test-data/recipes/correct-sha/recipe.yaml

feat: accept multiple urls for url source and use them as mirrors

---

src/lib.rs
src/recipe/jinja.rs
src/recipe/parser.rs
src/recipe/parser/requirements.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__requirements__test__compiler_serde-2.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__requirements__test__compiler_serde.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__requirements__test__pin_package.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__complete_recipe.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/render/pin.rs
src/render/resolved_dependencies.rs
src/render/snapshots/rattler_build__render__resolved_dependencies__tests__dependency_info_render.snap
src/selectors.rs
src/snapshots/rattler_build__metadata__test__curl_recipe.yaml.snap
src/used_variables.rs
src/variant_config.rs
test-data/rendered_recipes/curl_recipe.yaml

For compatibility with recent conda-forge efforts we're implementing the `stdlib` jinja function. 
Open questions:
- should there be any default values?
- compiler and stdlib currently evaluate to an intermediate form. Should we keep that?
- If we decide for the intermediate form, we should allow the function only in specific sections such as:
- requirements.*
- ignore_run_exports / from_package
- And then we should also disallow it in the `test` section and only allow the `compiler-c` or `compiler-cxx` packages in the test section.

feat: `stdlib` implementation

---

src/recipe/jinja.rs
src/recipe/parser/requirements.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__requirements__test__pin_package.snap
src/render/pin.rs
src/render/resolved_dependencies.rs
src/render/snapshots/rattler_build__render__resolved_dependencies__tests__dependency_info_render.snap
test-data/pins.yaml
test/end-to-end/test_simple.py

This follows the comment by @h-vetinari and @chenghlee. 
It removes `max_pin` and `min_pin` arguments, and instead only `lower_bound` and `upper_bound` are accepted with three values:
- None (no upper or lower bound)
- `x.x...` "pin expression"
- `1.2.3` a version

feat: simplify jinja pin expressions

---

src/script.rs
test-data/recipes/script/recipe.yaml
test-data/recipes/script/recipe_with_extensions.yaml
test-data/recipes/script/script.bat
test-data/recipes/script/script.sh
test/end-to-end/test_simple.py

currently, explicit (relative) paths don't work. This PR unifies how we are searching for files and fixes that behavior.

fix: unify how script files are found and fix a regression with explicit paths

---

src/render/resolved_dependencies.rs

fix: filter `run_exports` by direct specs more logically

---

src/recipe/jinja.rs

As of `0.17.0` (with the introduction of the checks for `compiler()` function usage), the integration tests for `conda-recipe-manager` showed some failures with `go` projects in `conda-forge`:
```
╭─ Finding outputs from recipe
│
╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe
Error:   × Parsing: failed to render Jinja expression: undefined value: No compiler found for language: go-nocgo
│ You should add `go-nocgo_compiler` to your variant config file. (in <string>:1)
╭─[22:7]
21 │   build:
22 │     - ${{ compiler('go-nocgo') }}
·       ─────────────┬─────────────
·                    ╰─┤ undefined value: No compiler found for language: go-nocgo
·                      │ You should add `go-nocgo_compiler` to your variant config file.
23 │     - if: unix
╰────
``` …

Adds commonly used go compilers to default compiler logic

---

src/recipe/parser/script.rs
src/script.rs

I overlooked a condition where we have a simple (single-line) script and a `cwd` (as injected by the test serialization. 
Under these conditions, we did not render out the `cwd` and thus the test execution stopped working.
This PR has the fix.

fix: fix a serialization issue where a single-line script and cwd are set

---

Cargo.lock
Cargo.toml
docs/index.md
docs/reference/cli.md
src/main.rs
src/opt.rs

Corresponding to https://github.com/prefix-dev/pixi/pull/1599

feat: Add nushell completions

---

.github/workflows/rust.yml
.pre-commit-config.yaml
src/package_test/content_test.rs
src/recipe/jinja.rs
src/recipe/parser.rs
src/recipe/parser/glob_vec.rs
src/recipe/parser/test.rs
src/render/pin.rs
src/render/resolved_dependencies.rs
src/source/extract.rs

Also remove `paths` filter for CI.
It doesn't play well with concurrency.
If you add a job that doesn't touch the correct files, it will cancel other jobs, but not start a new one.

chore: fix clippy warnings

---

docs/highlevel.md

The numbering was broken because of the new-lines
Before:
After:

docs: Fix markdown list

---

docs/reference/jinja.md
mkdocs.yml

I've noticed that the [CEP](https://github.com/conda/ceps/blob/81d9515782de7e896e6e4e00da05f4f31407ab78/cep-recipe-jinja.md) has nice docs on how our jinja usage works.
So I copied that part to the `rattler-build` docs

docs: improve jinja documentation

---

src/main.rs

I've noticed that `rattler-build` fails if you run it quickly twice with the same recipe, since the tempdir already exists.
This PR fixes it.

chore: Use tempfile crate instead of implementing it ourselves

---

.github/workflows/rust.yml
Cargo.toml
src/lib.rs
src/main.rs
src/opt.rs

This adds rip as an optional and makes the recipe-generation module gated behind a feature. This is done only for the `lib` the `bin` has that feature as required.
~~Will be a draft until we verify that this works.~~

feat: make recipe generation optional

---

src/cache.rs
src/packaging/metadata.rs
src/source/copy_dir.rs
test-data/recipes/cache/recipe-symlinks.yaml
test/end-to-end/__snapshots__/test_simple/test_symlink_recipe.json
test/end-to-end/__snapshots__/test_symlinks/test_symlink_cache.json
test/end-to-end/conftest.py
test/end-to-end/helpers.py
test/end-to-end/test_simple.py
test/end-to-end/test_symlinks.py

This might fix #992 
I should add a test tomorrow.

fix: replace absolute symlinks from cache with correct version

---

src/recipe/parser/requirements.rs
src/render/resolved_dependencies.rs
src/render/run_exports.rs
test-data/recipes/cache_run_exports/helper.yaml
test-data/recipes/cache_run_exports/recipe_test_1.yaml
test-data/recipes/cache_run_exports/recipe_test_2.yaml
test-data/recipes/cache_run_exports/recipe_test_3.yaml
test/end-to-end/test_simple.py

this is an attempt to fix #977 
I think part of the issue was (at least!) that we didn't use the right "ignore_run_exports" (ie. not the one from the cache. 
My quick test showed that it still doesn't fix the issue, so will have to dig a little bit more tomorrow. But should be fixed swiftly!

fix: filter cache run_exports with the right ignores

---

docs/tutorials/python.md

A couple of reasons for these changes:
- the current example for numpy 1.26.4 uses a couple of submodules that no longer exist
- the NumPy C API export changed a lot, so advertise that (and no longer use `pin_subpackage`)
- there's a second entrypoint in numpy 2.0 (`numpy-config`) that's also nice to add
- the build/host split may be confusing to the reader, since it contradicts what is explained in the cross compiling docs ("tools that run on the build machine go under `build:`"); the current setup only makes sense when using `crossenv`, like conda-forge does.

docs: update numpy recipe in Python examples page

---

.github/workflows/rust.yml
.pre-commit-config.yaml

Add `--workspace` flag. That way it is run on the whole workspace.

ci: run `clippy` on the whole workspace

---

.github/workflows/end-to-end.yml

It used to be filtered by path which doesn't mix well will required jobs

ci: always run on push and PR

---

src/bin/generate-cli-docs.rs
src/build.rs
src/env_vars.rs
src/lib.rs
src/metadata.rs
src/opt.rs
src/packaging.rs
src/packaging/metadata.rs
src/recipe/parser.rs
src/recipe/parser/build.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/tui/render.rs
src/tui/state.rs
src/variant_config.rs

The `build` string in the recipe was an optional value in name only. The code always assumed it has a value, which it always got during parsing. This PR changes this behavior so that the recipe datastructure actually contains an optional build but the code uses `Output::build_string()` to get the actual builds string which is either based on the hash or on the user-defined value.
This also allowed me to remove a bunch of unwraps.
I also reformatted some files with the nightly formatter.

refactor: make build string optional in recipe

---

Cargo.lock
Cargo.toml
docs/reference/cli.md

The CLI docs were outdated. I've updated them by running `pixi run generate-cli-docs`.
No idea why so much changed here.

fix: CLI docs

---

src/recipe/jinja.rs

The current implementation of `git.latest_tag` seems a bit off. Using `-v:refname` together with `last()` is actually selecting the earliest tag, not the latest one. 
One can check this by 
```yaml
context:
git_repo_url: https://github.com/prefix-dev/rattler-build.git
latest_tag: ${{ git.latest_tag( git_repo_url ) }}
package:
name: "rattler"
version: ${{ latest_tag }}
source:
git: ${{ git_repo_url }}
tag: ${{ latest_tag }}
```

fix: latest_tag get oldest tag

---

src/cache.rs
src/metadata.rs
src/package_test/run_test.rs
src/recipe/custom_yaml/rendered.rs
src/recipe/parser.rs
src/recipe/parser/script.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__binary_relocation.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__binary_relocation_paths.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__complete_recipe.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__jinja_sequence.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__map_null_values.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/script.rs
src/snapshots/rattler_build__metadata__test__curl_recipe.yaml.snap
src/snapshots/rattler_build__metadata__test__read_recipe_with_sources.snap
src/snapshots/rattler_build__metadata__test__rich_recipe.yaml.snap
test-data/rendered_recipes/curl_recipe.yaml
test-data/rendered_recipes/git_source.yaml
test-data/rendered_recipes/rich_recipe.yaml

This delays the Jinja evaluation for the `script` contents. That means that we can also inject a lot of variables into the script by using `jinja`. 
Such as `${{ PREFIX }}` or `${{ PYTHON }}`. 
For example the following two examples work on Windows and on Unix:
```yaml
build:
script: cargo install --root ${{ PREFIX }} .
script: ${{ PYTHON }} -m pip install .
```
These variables are also available as environment variables. However, since we are using `cmd.exe` and `bash` on the different operating systems, the syntax to expand environment variables is not the same (`%PREFIX%` vs `$PREFIX`).
Alternatives we considered (or are considering):
- add a jinja function `env("PREFIX")` that expands to either `%PREFIX%` or `$PREFIX` depending on execution context. Might not work well with different …

feat: delay jinja evaluation for script

---

src/source/git_source.rs

Previously, we'd capture and just throw the error messages away. Instead, format them with the returned error.

Include `git` output error context on git failures

---

src/render/solver.rs

@hadim this is the fix for `CONDA_OVERRIDE_CUDA` to work 🤦 
To be honest though, I would like to remove this in favor of explicit `system-requirements` in the recipe at some point.

detect virtual packages from environment

---

src/build.rs
src/lib.rs
src/package_test/run_test.rs

fix: use proper `host_platform` when testing `noarch` packages

---

src/env_vars.rs
src/lib.rs
src/opt.rs
src/recipe/jinja.rs
src/selectors.rs

@isuruf I started a PR here to add `--host-platform` to the arguments.
The current logic is:
The `host_platform` is defaulted to `Platform::current()`.
If `target_platform` is unset, then we initialize it to the value of `host_platform`.
If `target_platform` is set to something (noarch is forbidden to set btw), then `host_platform` is set to this value too, if it is not set explicitly (so the current logic continues to work).
Would be great if you let me know if that makes sense to you and what use-cases you had in mind.

support setting `host_platform` explicitly

---

src/source/git_source.rs

This fixes a bug where new branches, added after `src_cache` was originally cloned, wouldn't be able to be successfully checkout out. Fix by using a refspec which creates and destination branch/tag.

Format branch/tag refspecs for git-fetch as `<src>:<dst>`

---

src/source/git_source.rs
test-data/recipes/git_source_patch/recipe.yaml
test-data/recipes/llamacpp/recipe.yaml
test-data/recipes/package-content-tests/llama-recipe.yaml
test-data/recipes/variants/recipe.yaml

By default, git fetch/clone will download all tags from the remote repo, so pass `--no-tags` to avoid some unnecessary downloading -- we'll still explicitly fetch any tag we need to checkout.

Avoid fetching all tags on git clone/fetch

---

src/package_test/run_test.rs

This came up in https://github.com/conda-forge/sourmash-minimal-feedstock/pull/64

fix: running python test cross-platform

---

src/source/copy_dir.rs

fs::copy copies the permissions, but reflink (on Linux, btrfs) does not.

fix: copy permissions when reflinking files

---

src/lib.rs
src/package_test/run_test.rs
src/packaging.rs
src/script.rs
src/source/mod.rs
src/source/url_source.rs

This now replaces more paths (on Windows, especially) with shorter variables.

feat: improve path display and replacement during script execution

---

src/script.rs
src/windows/env.rs

This mirrors `conda-build` behavior that also prepends these variables:
https://github.com/conda/conda-build/blob/651b941b2db94d46f5f343acf2d7d931b10c1d90/conda_build/windows.py#L267-L270

insert `LIB` and `INCLUDE`

---

src/used_variables.rs
src/variant_config.rs
test-data/recipes/output_order/order_1.yaml
test-data/recipes/pin_subpackage/recipe.yaml
test/end-to-end/test_simple.py

And also fixes the "used-variables" detection for `pin_subpackage` to not detect strings, but properly detect variables.
Going to include @pavelzw test from #1120

fix dot in variant when exporting to environment

---

src/env_vars.rs

fix: npy version issue

---

src/script.rs

Scripts with no shebang are blocked by certain endpoint security tools, failing the rattler build at hand. Adding a bash shebang to the bash preamble should fix this issue.

add shebang to bash preamble

---

src/source/git_source.rs

Fix missing recipe_dir.join() for git paths

---

src/script.rs

We returned to early and then didn't render multi-line scripts with Jinja, such as:
```yaml
script: |
foo
bar ...
```

fix: multiline script render

---

Cargo.lock
Cargo.toml
rust-tests/Cargo.toml
src/metadata.rs
src/packaging.rs
src/packaging/metadata.rs
src/post_process/python.rs
src/recipe/parser/build.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__complete_recipe.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
test-data/recipes/test-parsing/single_output.yaml

This adds a new field:
```yaml
package:
name: python
build:
python:
site_packages_path: foo/bar/...
```
This field is only valid for packages with `name: python`.

feat: implement CEP-17 and prepare release

---

docs/reference/cli.md
docs/reference/recipe_file.md
docs/tutorials/javascript.md
docs/tutorials/python.md
examples/rich/recipe.yaml
src/recipe/parser/source.rs
src/source/url_source.rs

This improves the URL source type in two ways:
- file:/// urls are treated exactly the same as remote urls. We copy the file to the cache, and extract it.
- Extraction is now conditional on a "file_name". If a file_name is set, we will rename the archive to the file_name value and insert it as an archive in the work dir. This helps for example when packaging a NPM package as it seems to work better from an archive :)

fix: url source extraction for file:/// urls

---

README.md
docs/index.md
docs/reference/recipe_file.md
examples/mamba/build_mamba.bat
examples/mamba/build_mamba.sh
examples/rich/recipe.yaml
src/snapshots/rattler_build__metadata__test__rich_recipe.yaml.snap
test-data/recipes/flask/recipe.yaml
test-data/recipes/package-content-tests/rich-recipe.yaml
test-data/recipes/rich/recipe.yaml
test-data/recipes/toml/recipe.yaml
test-data/recipes/variants/boltons_recipe.yaml
test-data/rendered_recipes/rich_recipe.yaml

Motivated by https://github.com/conda/grayskull/issues/582 and @wolfv's comment https://github.com/conda/grayskull/issues/582#issuecomment-2480480976
* Remove `--no-deps`, `--no-build-isolation`, and `--ignore-installed` `pip install` options in recipes as `rattler-build` will enforce all required `pip install` options itself at build time.
c.f.
https://github.com/prefix-dev/rattler-build/blob/665125d565c47bca84a831e9a29cb19ddcfa2773/src/env_vars.rs#L230-L239

docs: Remove 'pip install' options in recipes

---

src/package_test/serialize_test.rs
src/source/copy_dir.rs

Should fix #1180 
I think it's fine to not use gitignore in these cases. We'll switch to [`wax`](https://docs.rs/wax/latest/wax/) for this in the future anyways.

do not use gitignore when copying test files

---

docs/experimental_features.md

'1' is not a valid value for boolean env, apparently:
```
> RATTLER_BUILD_EXPERIMENTAL=1 rattler-build build
error: invalid value '1' for '--experimental'
[possible values: true, false]
```
(arguably, it would be more expected for the documented `EXPERIMENTAL=1` to actually work, since it's a far more common pattern than string true/false in env).

doc: fix experimental env

---

src/package_test/serialize_test.rs

We were not properly embedding the contents of script files in the tests. This fixes that.
Fixes #1212

fix: resolve file contents properly

---

docs/variants.md

It seems `variant_config` is now `variant`.

Fixed wrong key name in doc

---

Cargo.lock
Cargo.toml
src/metadata.rs
src/recipe_generator/pypi.rs
src/render/resolved_dependencies.rs
src/render/solver.rs

Updates the middleware and RIP. So that we can use these in the pixi build backends and is compatible with the lattest rattler main branch (which is unreleased).

feat: upgrade middleware and rip

---

src/build.rs

Fix https://github.com/prefix-dev/rattler-build/issues/1149
The change in `build.rs` fixes the `--no-test` arg causing the repodata.json to not be regenerated after a package was built.

fix: reindex output cache after build (#1149)

---

src/build.rs
src/lib.rs
src/opt.rs
src/tool_configuration.rs

I needed a way to change the channel priority due to having a similar situation as the op of this issue https://github.com/prefix-dev/rattler-build/issues/343
I'm new to rust so there's probably a better way of adding it as a cli arg without the wrapper but I couldn't figure it out

feat: add `--channel-priority={strict|disabled}`

---

src/metadata.rs

This was tripping up `pixi build` for some reason. I think this is better anyways.

fix: create intermediate directories as well

---

src/render/solver.rs
src/script/interpreter/bash.rs
src/script/interpreter/cmd_exe.rs
src/script/interpreter/mod.rs
src/script/interpreter/nushell.rs
src/script/interpreter/perl.rs
src/script/interpreter/python.rs
src/script/mod.rs

This adds `perl` as an interpreter, and I verified that the following "works":
```yaml
package:
name: test-perl-exec
version: "0.1.0"
build:
script:
interpreter: perl
content: |
use strict;
use warnings;
use Config;
print "Hello World!\n";
print "Perl prefix: $Config{prefix}\n";
requirements:
build:
- perl
```
We can add support for `R`, `nodejs`, and a number of other languages in the same way.
cc @danielnachun

feat: refactor script and add `perl` as an interpreter

---

src/linux/link.rs
src/macos/link.rs
src/unix/mod.rs
src/unix/permission_guard.rs

There was an issue on macOS where relinking did not work, because the file was `read-only`.
This fixes it, but I also need to check wether the same problem occurs on Linux.

fix: allow relinking on read-only files

---

src/recipe/parser.rs
src/render/solver.rs

We need it from pixi-build-backend side to setup entry points

feat: expose python as struct

---

py-rattler-build/rattler_build/__init__.py
src/build.rs
src/cache.rs
src/lib.rs
src/metadata.rs
src/opt.rs
src/recipe/parser/cache.rs
src/recipe/parser/output.rs
src/recipe/parser/source.rs
src/snapshots/rattler_build__metadata__test__curl_recipe.yaml.snap
src/snapshots/rattler_build__metadata__test__read_recipe_with_sources.snap
src/snapshots/rattler_build__metadata__test__rich_recipe.yaml.snap
src/source/mod.rs
src/system_tools.rs
test-data/recipes/cache/recipe-symlinks.yaml
test/end-to-end/__snapshots__/test_symlinks/test_symlink_cache.json
test/end-to-end/test_symlinks.py

This PR enables the caching of the source folder, too. 
This meant we had to change the behavior a bit:
- cache has to be restored to the _exact_ same prefix. That means every output will build in the same directory (should also fix the Windows bug!). For this, we currently use the name of the first output (we don't have the `recipe.name` available, but that could be fixed).
- ~~When the cache is involved, we don't fetch sources for the outputs. We should, however, change this to fetch the "diff" of the sources. Sources that were already fetched for the cache should not be re-fetched, but additional sources should be added on top (user has to make sure that there is no clobbering.~~ Cache has its own source section now.
These changes made the example at …

feat: cache sources too

---

docs/tutorials/perl.md
mkdocs.yml

Pinging @danielnachun for review

docs: add some perl docs

---

src/tool_configuration.rs

This should fix users with slower internet connection. Currently, a package can download only for 5 minutes - which is definitely not appropriate for some larger ones.
With the `read_timeout` this value is reset at every read so only really stalled connections will time out.
similar change in pixi: https://github.com/prefix-dev/pixi/pull/1329

fix: use read timeout, not global timeout

---

docs/reference/recipe_file.md
src/packaging.rs
test/end-to-end/test_simple.py

So far we were erroring if the same license file was added from both the source directory and the recipe directory. Now we are issueing a warning and prefer the license from the recipe directory.
In practice, it would be much better to remedy this by using different license names or removing the license from the recipe folder.
fixes https://github.com/prefix-dev/rattler-build/issues/1173

fix: license from recipe folder instead of erroring if both are found

---

src/packaging.rs
src/recipe/custom_yaml.rs
src/recipe/parser/script.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__test__test__script_parsing.snap
src/variant_render.rs

I think I prefer to keep the original order of env vars. In the future, we might allow "rendering" the env vars etc.

feat: use index map for env

---

src/render/resolved_dependencies.rs
test-data/recipes/recipe_variant/recipe.yaml
test/end-to-end/__snapshots__/test_simple/test_recipe_variant_render.1.json
test/end-to-end/__snapshots__/test_simple/test_recipe_variant_render.json
test/end-to-end/test_simple.py

fixes #1266 
Also fixes that we apply variants to the run dependencies, which should not have happened.

fix: variant issue with `__unix`

---

docs/reference/recipe_file.md

Fix the example in "the env Jinja functions" part of recipe documentation to use `${{ hash }}` rather than `${{ PKG_HASH }}`, as the latter does not work.

fix: Fix "the env Jinja functions" example not to ref PKG_HASH

---

Cargo.lock
Cargo.toml

Even though it's a default feature, we're using default-features = false, so this was missing.

speed up prefix record loading

---

src/lib.rs

Fix https://github.com/prefix-dev/rattler-build/issues/343
After https://github.com/prefix-dev/rattler-build/pull/1211 was merged some of the code for the build/rendering/testing was refactored and one of the changes used the old `ChannelPriority::Strict` value instead of `tool_config.channel_priority`
https://github.com/prefix-dev/rattler-build/commit/2c7f0e9f513679e8169a2307ef094b9bde9ee71d#diff-be833857e8bbf63e2cbb12410f1e722789c4dce3d8c1dde47a79af89e52c71dcL201
https://github.com/prefix-dev/rattler-build/commit/2c7f0e9f513679e8169a2307ef094b9bde9ee71d#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R521

fix: Use tool_configuration.channel_priority in TestConfiguration

---

src/lib.rs
src/opt.rs
src/upload/anaconda.rs
src/upload/conda_forge.rs
src/upload/mod.rs
src/url_with_trailing_slash.rs

closes #1254
tested out locally with my artifactory instance, seems to work flawlessly

fix: Use UrlWithTrailingSlash for upload, use bearer auth for Artifactory upload

---

Cargo.lock
Cargo.toml
src/cache.rs
src/lib.rs
src/main.rs
src/metadata.rs
src/opt.rs
src/package_test/run_test.rs
src/recipe_generator/pypi.rs
src/script/interpreter/bash.rs
src/script/interpreter/cmd_exe.rs
src/script/interpreter/nushell.rs
src/script/mod.rs
src/script/sandbox.rs

This is an experiment on what usage of the new `rattler` sandbox could look like. 
Works like a charm on macOS!

feat: add experimental sandbox during builds

---

py-rattler-build/Cargo.lock
py-rattler-build/Cargo.toml
py-rattler-build/pixi.lock
py-rattler-build/pixi.toml
py-rattler-build/pyproject.toml
py-rattler-build/rattler_build/__init__.py
py-rattler-build/src/lib.rs
py-rattler-build/tests/data/recipes/dummy/recipe.yaml
py-rattler-build/tests/unit/conftest.py
py-rattler-build/tests/unit/test_basic.py
src/console_utils.rs
src/lib.rs
src/macos/link.rs
src/main.rs
src/opt.rs
src/recipe/jinja.rs
src/source/copy_dir.rs
src/source/extract.rs
src/tui/mod.rs
src/tui/state.rs

This PR extends the Python API of rattler build in order to build a recipe.
It can be used as follows:
```python
import rattler_build
rattler_build.build_recipe(recipe_path, output_dir)
```
`output_dir` is an optional parameter.
The PR also refactors the build logic, to be less entangled with CLI parsing.
Some options still appear, since it would have blown up the PR size, but `BuildOpts` have been replaced with a different struct `BuildData` in the core logic.

feat: continue py-rattler-build

---

rust-tests/src/lib.rs
src/recipe/parser/script.rs

An attempt to fix https://github.com/prefix-dev/rattler-build/issues/1335
See below:
```yaml
build:
script:
content:
- ${{ PYTHON }} --version
build:
script:
content: ${{ PYTHON }} --version
build:
script:
- ${{ PYTHON }} --version
build:
script: ${{ PYTHON }} --version
```
This issue being that the jinja variables are removed from the string. So `${{ PYTHON }} --version` becomes ` --version` during the build.
---
Should I add test(s) for this? If yes then where?

Fix removed jinja variable in `build.script.content`

---

src/lib.rs
src/variant_render.rs

Fixing a problem with the new ABI3 / CEP20 implementation as discussed with @isuruf: https://github.com/conda-forge/atomic-counter-feedstock/pull/8

fix: use python key, and improve skip output

---

src/render/solver.rs

Thanks for `rattler-build`!
As I watch more builds, I noticed that the logged solve table doesn't 
right-align package sizes, making it rather hard to do any kind of visual comparison. 
```
│ │ ╭──────────────────┬────────────┬────────────────────┬─────────────┬────────────╮
│ │ │ Package          ┆ Version    ┆ Build              ┆ Channel     ┆ Size       │
│ │ ╞══════════════════╪════════════╪════════════════════╪═════════════╪════════════╡
│ │ │ _libgcc_mutex    ┆ 0.1        ┆ conda_forge        ┆ conda-forge ┆ 2.50 KiB   │
│ │ │ _openmp_mutex    ┆ 4.5        ┆ 2_gnu              ┆ conda-forge ┆ 23.07 KiB  │
│ │ │ bzip2            ┆ 1.0.8      ┆ h4bc722e_7         ┆ conda-forge ┆ 246.86 KiB │
│ │ │ ca-certificates  ┆ 2024.12.14 ┆ hbcca054_0         ┆ conda-forge ┆ 153.41 KiB │
│ │ │ …
```

right align size in solve table

---

src/lib.rs
src/source_code.rs

This makes error messages nicer and even clickable (in VSCode).
fixes https://github.com/prefix-dev/rattler-build/issues/1238

feat: attach file name to source code in error message

---

.github/workflows/python-bindings.yml
py-rattler-build/Cargo.lock
py-rattler-build/pixi.toml
py-rattler-build/src/lib.rs

- Update lock file to make it compile again
- Ensure on CI that lock file is up-to-date
- Ensure that warnings fail on CI
- Fix clippy lints

fix: update lock file of python bindings

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
py-rattler-build/Cargo.toml
rust-tests/Cargo.toml
src/tool_configuration.rs

Installing https://github.com/killercup/cargo-edit and running `cargo upgrade --incompatible=allow` does the trick

chore: Update dependencies of rattler-build and py-rattler-build

---

README.md
docs/automatic_linting.md
docs/index.md
docs/reference/recipe_file.md
examples/cargo-edit/recipe.yaml
examples/curl/recipe.yaml
examples/mamba/recipe.yaml
examples/rich/recipe.yaml
examples/ros-humble-turtlebot4-msgs/recipe.yaml
test-data/recipes/allow_missing_dso/recipe.yaml
test-data/recipes/correct-sha/recipe.yaml
test-data/recipes/empty_folder/recipe.yaml
test-data/recipes/git_source/recipe.yaml
test-data/recipes/globtest/recipe.yaml
test-data/recipes/llamacpp/recipe.yaml
test-data/recipes/overdepending/recipe.yaml
test-data/recipes/overlinking/recipe.yaml
test-data/recipes/pkg_hash/recipe.yaml
test-data/recipes/polarify/recipe.yaml
test-data/recipes/private-repository/recipe.yaml
test-data/recipes/read_only_build_files/recipe.yaml
test-data/recipes/rich/recipe.yaml
test-data/recipes/rpath/recipe.yaml
test-data/recipes/run_exports_from/recipe.yaml
test-data/recipes/toml/recipe.yaml
test-data/recipes/zip-source/recipe.yaml

This is not necessary anymore. Naming the recipe `recipe.yaml` is good enough.

docs: remove schema link

---

docs/tutorials/cpp.md

Without this fix, non-Windows tests fail complaining that `/share/cmake/xtensor/xtensorConfig.cmake` does not exists.

docs: Fix package_contents tests in xtensor example

---

docs/build_options.md

This PR closes #1447. I've chosen to update the documentation rather than change the behavior since changing the default will be a breaking change that will likely cause currently working package builds to fail.

Update docs on overlinking and overdepending

---

docs/reference/recipe_file.md
src/recipe/error.rs
src/recipe/parser.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__context_value_not_scalar.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__context_value_not_uniform_list.snap
src/recipe/variable.rs
test-data/recipes/jinja-types/recipe.yaml
test/end-to-end/__snapshots__/test_simple/test_jinja_types.json
test/end-to-end/test_simple.py

Add support for specifying lists in addition to scalars in `context`. They are converted to Jinja sequences.
This is literally the first Rust code I have written, so it's probably horrible. I consider it a miracle that it works. I appreciate any hints to make it cleaner. I also need to add error handling, and tests.
rattler_build_conda_compat needs updating too.

feat: support lists in "context" (#1289)

---

src/macos/link.rs

During recodesign after dynamic relocation, we drop entitlements and requirements stored on the binary. These are important to keep, especially for debuggers like lldb, which need certain entitlements like com.apple.security.get-task-allow which ad-hoc signed apps don't have default so they can attach to other processes. 
Long term, we should expose more options to set signing identities, explicit signing requirements, and other options. This is especially important if we want to allow GUI apps to be in conda-forge that can be directly launched without first launching a signed terminal process.

fix: preserve macOS entitlements and requirements in codesign

---

Cargo.lock
Cargo.toml
docs/reference/cli.md
py-rattler-build/Cargo.lock
src/lib.rs
src/opt.rs
src/upload/mod.rs
test/end-to-end/test_simple.py

Since `rattler-index` and `rattler-build` are typically used together for S3-based channels, they should offer the same CLI.
Additionally, it makes sense to use the more lightweight opendal S3 crate for interactions with S3 buckets (similar to `rattler-index`).

refactor: Align CLI for s3 with rattler-index

---

src/macos/link.rs
src/post_process/relink.rs
src/system_tools.rs

@zbowling unfortunately, conda-forge ships and uses `sigtool` which advertises itself as `codesign` as well, but does not support these extra options. 
My current idea is to:
- use extra options if `/usr/bin/codesign` is the codesign
- not use extra options if we find codesign somewhere else
Unfortunately neither `sigtool "codesign"` nor `codesign` have a `--version` that we could use easily. 
Their `--help` outputs do look differnet though, so we could also use that as indicator.
Or we could first try with the extra args, and if it fails, fall back ... 
Happy to hear other thoughts. Also pinging @minrk who uncovered all of this.

fix: properly raise error if macOS `codesign` - ing fails

---

src/macos/link.rs
test-data/recipes/test-relink/absolute.c
test-data/recipes/test-relink/build.sh
test-data/recipes/test-relink/recipe.yaml
test-data/recipes/test-relink/relative.c
test-data/recipes/test-relink/test_link.c
test/end-to-end/test_simple.py

_similar_ to conda-build, but not the same. conda-build [searches a lot more](https://github.com/conda/conda-build/blob/61e9bb24588d8b353321c11de5452d57aa2f85ca/conda_build/post.py#L386-L412), and sets the link to find any matching file anywhere in the package, whereas this only handles the case where it's in $PREFIX/lib.
This also fixes an erroneous check for absolute path install_name for dylibs in $prefix/lib. The check was `strip_prefix(prefix)` whereas it should have been `strip_prefix(encoded_prefix.join("lib"))` if it were to match the path of absolute install_names.
I'm not sure how to add a test for this in this repo, but [this sample recipe](https://github.com/minrk/test-recipe/tree/relink) is fixed by it.
closes #1476
(feel free to ignore my code and rewrite with your own fix, …

mac: relink 'libfoo.dylib' as '@rpath/libfoo.dylib'

---

.github/workflows/rust.yml
rust-tests/src/lib.rs
src/package_test/content_test.rs
src/recipe/parser.rs
src/recipe/parser/glob_vec.rs
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_all_or_globvec.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_globvec-2.snap
src/recipe/parser/snapshots/rattler_build__recipe__parser__glob_vec__tests__parsing_globvec.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__complete_recipe.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap
src/source/copy_dir.rs
test-data/recipes/globtest/recipe.yaml
test/end-to-end/test_simple.py

This would fix #1055 but needs more work because it doesn't compile right now. Idea is to store the "source" glob alongside the evaluated glob for better serialization. Also later we need this sometimes to change how the glob behaves in the package content tests (where we amend it with e.g. `*.so`.

glob folders as well from simple name

---

.github/workflows/docs.yml
.github/workflows/end-to-end.yml
.github/workflows/enforce-sha.yaml
.github/workflows/pre-commit.yml
.github/workflows/python-bindings.yml
.github/workflows/python-release.yml
.github/workflows/rust.yml

- pin external actions
- enforce sha also in the future
For motivation see https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised and https://michaelheap.com/pin-your-github-actions/

ci: pin github actions

---

src/recipe/parser/package.rs
src/recipe/parser/requirements.rs
test-data/recipes/test-parsing/recipe_ignore_run_exports.yaml
test/end-to-end/test_simple.py

Fixes https://github.com/prefix-dev/rattler-build/issues/1445
```
package:
name: mypkg
version: '0.1.0'
build:
number: 0
requirements:
ignore_run_exports:
from_package:
- ${{ compiler('cxx') }}
build:
- ${{ stdlib('c') }}
- ${{ compiler('c') }}
- ${{ compiler('cxx') }}
```
```
c_compiler:
- clang
c_compiler_version:
- '16'
c_stdlib:
- macosx_deployment_target
c_stdlib_version:
- '11.0'
cxx_compiler:
- clangxx
cxx_compiler_version:
- '16'
```
Results in (i am on windows btw, just wanted to exactly reproduce the issue so used the same macos deps)
```
╭─ Finding outputs from recipe
│ Loading variant config file: "recipe/issue_variant.yml"
│ Found 1 variants
│
│ Build variant: mypkg-0.1.0-h3ee991f_0
│
│ ╭──────────────────────┬────────────────────────────╮
│ │ Variant              ┆ Version …
```

fix(parser): enhance package name extraction logic in TryConvertNode

---

src/recipe/error.rs
src/recipe/parser.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__context_variable_with_hyphen.snap

closes #995
the issue was only mentioned the hyphen, i though dots would have a problem with jinja as well but i saw we already use `(jinja, &format!("context.{}", k.as_str()))?;` so i didn't continue with adding dots

feat: add error handling for hypen in context variables

---

src/main.rs

Essentially, it's the same thing we do here: https://github.com/prefix-dev/pixi/pull/2922
Wanted to preserve the error messages we get from main thread as well, so didn't use an wrapping/unwrapping approach but instead used `map_err` with join to preserve the error messages

refactor: improve stack handling by spawning a dedicated thread

---

src/recipe/parser/snapshots/rattler_build__recipe__parser__test__test__python_parsing.snap
src/recipe/parser/test.rs
test-data/recipes/python-version-spec/recipe.yaml
test/end-to-end/test_simple.py

closes #1493
I also change the args of the abi3 test to use --recipe, for some reason it would pick up the recipe file on the root folder without --recipe command. After improving the parser to use matchspec and making it more strict, it would just fail (since it was not using the correct recipe)

feat: validate python_version specs in recipe parser

---

src/script/mod.rs
test-data/recipes/line-breaks/recipe.yaml
test/end-to-end/test_simple.py

closes #1525
I needed some time to plan how to approach this. I had two options:
- Use async
- Use sync, spawn threads that wait for every line for output to reach them and return immediately
After some thinking and research specially reading this discussion https://users.rust-lang.org/t/avoid-async-rust-at-all-costs-comments-from-experts/105860/44 I decided to go with async approach since what we are dealing with about script's run returns are a lot close to network operations approach. So I decided to go with async approach. Checked the overall integration test result time, surprisingly it went from 118 seconds to 109 seconds now.
output: 
On the visual changes, the old version would display the script's end line straight in blue line (they would overlap with each other) so that's fixed …

feat: add CarriageReturnToNewline wrapper for async reading

---

test-data/recipes/ssl_test/recipe.yaml

@wolfv seems like their host is down so github runners are struggling, we are using badssl anyways so i removed them from recipe

chore: remove outdated URL from SSL test recipe

---

src/script/mod.rs

I think this is quite harmless and makes pixi global installed `bash` work much nicer on macOS.

fix: add `PWD` to env vars to fix some weird issues with conda-bash

---

Cargo.lock
Cargo.toml
benches/line_breaks.rs
py-rattler-build/Cargo.lock
src/script/mod.rs
test-data/recipes/ssl_test/recipe.yaml

this pr directly adds the condition to replace \r with \n only if the following character is not \n
also added some checks, like for empty buffers we just skip them so they dont overload the loop, plus i made sure to use smaller buffer threshold (32 bytes) which significantly sped up the output printing. since the github windows runner increased its time, we now don't scan chunks one by one we just directly process them. 
results are incredibly interesting, hopefully its not just my local machine
from 176.24 sec to 123 sec now
@wolfv would be perfect if you also tested it locally to check the e2e tests time

feat: optimize CarriageReturnToNewline for better performance with buffer processing

---

docs/authentication_and_upload.md
docs/reference/cli.md
src/upload/mod.rs

Fixes #1595.
* Update docs
* Add clearer error message if user uses endpoint URL with IPv4 address and doesn't use `--force-path-style`

docs: Fix s3 docs for force-path-style

---

src/utils.rs

closes #1431
It was extremely hard to reproduce this bug constantly, I could reproduce it 5 times, sixth time it would just vanish. The solution was obviously retrying for a few times after encountering the either OS error 5 or 32, so i just added unit tests that simulates this with a locked file.

feat: Implement retry logic for directory deletion on Windows

---

src/source/patch.rs

This was suggested by @wolfv and @anjos on the conda-forge Zulip channel.
Add log messages for every patch applied to the build. So that package maintainers can verify that all patches are being correctly applied to the build when debugging build issues.
rattler-build does not output any log messages when it applies a patch. The only place the patches are listed is in the "Files in package:" section, but that is at the end of the build and is not shown if the build fails.
conda-build does log patches. Below is the patch info displayed when building conda-forge/dtc-package-feedstock.
```
Applying patch: /home/conda/recipe_root/patches/0001-tests-sw_tree1.c-fix-unitialized-saveptr.patch
Applying patch: /home/conda/recipe_root/patches/0001-tests-sw_tree1.c-fix-unitialized-saveptr.patch with …
```

feat: add log messages for patches applied

---

examples/linking/recipe.yaml
src/post_process/checks.rs
src/post_process/package_nature.rs
src/windows/link.rs

We were collecting the libraries that a specific library / executable is linking against, but we were not yet matching it up against the libraries installed by other packages or the system.
This is fixed now and we get output that looks like this:
This should also give more meaningful overlinking and overdependening analysis results.

fix: properly link check on Windows

---

src/tool_configuration.rs

it would be nice to have a default constructor for the base client, and not panic on expect

fix: add a default constructor for the baseclient

---

src/variant_config.rs
test-data/recipes/abi3/recipe.yaml

fix: ignore python more for abi3 recipes

---

src/source/git_source.rs
test/end-to-end/test_simple.py

this should prove https://github.com/prefix-dev/rattler-build/discussions/1615 we are doing relative git url paths correctly, as seen in the test first we are looking at git paths correctly as URLs, and as a fallback mechanism we are looking at them locally
also finished a TODO in the original unit test to make it run more like a local
took me a while because i couldn't make the dummy git repo work with recipe files written by hand, so i opted to writing them on fly on the test instead

feat: add test for building recipes with relative Git source paths

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
src/packaging.rs
test/end-to-end/test_simple.py

closes #1262 hopefully, i am only confident with unit tests but hopefully it passes mac os!

feat: add Unicode normalization for path handling and detect case-insensitive filename collisions

---

src/linux/link.rs

fix: make `relink` on linux recognize `${ORIGIN}`

---

src/packaging/metadata.rs
src/recipe/error.rs
src/recipe/parser/package.rs

This was failing because the un-normalized name made it into the index.json and then into the `repodata.json`:
```yaml
package:
name: pyPept
version: "1.0"
tests:
- script:
- exit 0
```

fix: normalize index name

---

src/source/patch.rs

This PR should fix #1670 .
The problem seemed to be that (apparently) some versions of `git` use the root directory of the repository as the root of the files described in the patch. If the working directory is a subdirectory of some git repository, running `git apply` will silently fail with `Skipping patch <path in patch>` (if run with `--verbose`).
I could obverse this behavior by running rattler-build with some patches. Wait for failure because the patches arent applied and then.
1) manually try applying the patch and observing git ignoring it.
2) initialize a git repository inside the working directory with `git init`.
3) retry applying the patch, this time it works as expected.
I could only observe this behavior on ubuntu using:
```
> git --version
git version 2.34.1
```
I did not …

fix: `git apply` inside a subdirectory of a git repository

---

docs/reference/recipe_file.md

The reference spec in the docs mentions `test`, however the actual recipes use `tests`.

docs: fix typo in recipe spec

---

src/source/copy_dir.rs
test-data/recipes/url-source-with-ignore/recipe.yaml
test/end-to-end/test_simple.py

closes #1693
it was relatively easy to fix actually, what we did before was:
- `.git_ignore(self.use_gitignore)` was not respecting .gitignore files, not even respecting buut, this for some reason respected `.ignore` files on `WalkBuilder`
- Added a false flag on `WalkBuilder` to not to respect `.ignore` files, also added a test and buildscript to check the `cargo.toml` specially. I tried to use a local zip file so that we don't download zed archieve, but i think we lack the relative path approach for urls there. Which might be a good idea to add in another pr.

feat: disable .ignore files in source copying

---

src/script/interpreter/bash.rs
src/script/interpreter/cmd_exe.rs

We always printed the `debug` message, but that is a little misleading when the script actually errored.

fix: fix up error message

---

docs/package_spec.md
docs/reference/cli.md
src/recipe/parser/about.rs
src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
src/recipe/snapshots/rattler_build__recipe__parser__tests__unix_recipe.snap

closes https://github.com/prefix-dev/rattler-build/issues/1730

refactor: remove `license_url` from package specification and related structures

---

.gitignore
docs/reference/cli.md
pixi.toml
recipe.yaml

This is a simple POC adding support for `pixi build`. The motivation is to be able to simply and quickly test a custom `rattler-build` binary within a conda-forge feedstock. 
With this PR you can now tweak the `pixi.toml` of any feedstock that way:
```diff
@@ -3,20 +3,22 @@
-"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"
+# "$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"
-[project]
+[workspace]
name = "katago-feedstock"
version = "3.50.0"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/katago-feedstock"
authors = ["@conda-forge/katago"]
channels = ["conda-forge"]
-platforms = ["linux-64", "osx-64", "win-64"]
+platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]
+preview = ["pixi-build"] …
```

Add support  for `pixi build`

---

src/source/mod.rs

before: closes gh-1739
after:
```console
❯ rattler-build build     
╭─ Finding outputs from recipe
│ Found 1 variants
│ 
│ Build variant: foo-0.1.0-h60d57d3_0
│ 
│ ╭─────────────────┬─────────────╮
│ │ Variant         ┆ Version     │
│ ╞═════════════════╪═════════════╡
│ │ target_platform ┆ "osx-arm64" │
│ ╰─────────────────┴─────────────╯
│
╰─────────────────── (took 0 seconds)
Error:   × IO Error: failed to canonicalize path `/Users/lucascolley/programming/pixi-sandbox/temp3/bar`: No such file or directory (os error 2)
╰─▶ failed to canonicalize path `/Users/lucascolley/programming/pixi-sandbox/temp3/bar`: No such file or directory (os error 2)
❯ rattler-build build -v  
2025-06-24T16:21:00.237982Z DEBUG rattler_build::opt: Using mirrors: {}
2025-06-24T16:21:00.507120Z DEBUG …
```

fix: use `fs_err` for invalid source path

---

src/packaging.rs

This code should not warn anymore about: `foo/test.py` == `footest.py`

fix: add more unit tests and simplify normalize path logic

---

src/packaging.rs
test/end-to-end/test_simple.py

delimit case-insensitive file matches with newline-space-hyphen instead of comma-space

---

README.md

Since we're now using `diffy` for patch application we shouldn't ask users to install `patch` separately.

docs(README): remove outdated requirement on `patch` command

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
rust-tests/src/lib.rs
src/source/extract.rs
src/source/mod.rs
src/source/url_source.rs
test-data/recipes/7z-source/recipe.yaml

feat(extract): extract 7zip files

---

src/post_process/relink.rs

The current implementation([1](https://github.com/prefix-dev/rattler-build/blob/a40d91cacce345a40c8fa4ab6eddb99ecce77995/src/post_process/relink.rs#L188), [2](https://github.com/prefix-dev/rattler-build/blob/a40d91cacce345a40c8fa4ab6eddb99ecce77995/src/packaging/file_mapper.rs#L108)) uses paths prefixed with `tmp_dir` like `/tmp/riscv-toolsrhLUlq/riscv-tools/bin/riscv64-unknown-elf-c++`.
This causes a mismatch with the configured glob patterns in `dynamic_linking.binary_relocation`, which expect paths relative to the prefix:
```
build:
dynamic_linking:
binary_relocation:
- riscv-tools/bin/**
- riscv-tools/include/**
- riscv-tools/lib/**
- riscv-tools/libexec/**
- riscv-tools/riscv64-unknown-elf/**
- riscv-tools/riscv64-unknown-linux-gnu/**
- riscv-tools/share/**
```
As a result, entries …

fix: use relative path for binary relocation glob match

---

docs/reference/recipe_file.md

I often can't find the build script environment settings. So, I added the link to build_script.md in the build script section to make it easy to find the build/script configurations.

Add the link to build script page from recipe page.

---

src/lib.rs
src/opt.rs
test/end-to-end/test_variant_override.py

This adds a new CLI interface to select / override variants.
For example, to build for a specific Python version, you can now pass:
```
rattler-build build --recipe ./example/foobar --variant python=3.13
```

feat: add variant override CLI and test

---

docs/reference/cli.md
pixi.toml

Otherwise, we might get problems with CI like the one in #1866, where a lint error occurs in a seemingly unrelated place.

fix: run clippy with all features

---

docs/build_options.md
docs/build_script.md
docs/compilers.md
docs/reference/cli.md
docs/tutorials/python.md
docs/variants.md
src/variant_config.rs

Fixes #1868 by throwing an error if the user accidentally passes a flat list instead of a nested list for `zip_keys`.
Also updates docs since it references variants_config.yaml but looks like rattler-build has now standardized on `variants.yaml` as the auto-detected filename for variants.

Enhanced zip_keys parsing to detect flat lists

---

docs/rebuild.md

Was checking out this feature and saw the docs don't match the CLI (0.47.0) `--package-file` flag

Add flag arg to rebuild.md

---

src/build.rs
src/cache.rs
src/lib.rs
src/render/resolved_dependencies.rs
src/render/solver.rs
test/end-to-end/helpers.py
test/end-to-end/test_simple.py

closes https://github.com/prefix-dev/rattler-build/issues/1880
i also think we shouldnt download these packages while running `--render-only --with-solve` as it makes sense and our current behavior would be too confusing. as to provide solvability we dont need to download the packages, we only need the index metadata anyways.
the only change was done to rattler-build build for `--render-only --with-solve` flag.

fix: disable run_exports extraction in render-only solves

---

src/recipe_generator/serialize.rs

we were not showing any info about creating a backup (which i think is not good, we shouldn't hide it from user), also changed the printin to use tracing instead

feat: add tracing logs for generating recipe file backup and write operations

---

src/variant_config.rs

There wasn't any reason to wrap this function

fix: simplify `load_conda_build_config`

---

src/cache.rs

Should fix https://github.com/prefix-dev/rattler-build/issues/1902

fix: return proper error instead of unwrapping

---

src/windows/link.rs

fix: skip uninterpretable PE files during relinking

---

.github/workflows/python-bindings.yml
py-rattler-build/pixi.lock
py-rattler-build/pixi.toml
py-rattler-build/pyproject.toml
src/source/patch.rs

Get's rid of some manual tasks in place of `pixi-build` compiling / linking things for us :)

feat: use `pixi-build` to build the Rust - Python bindings

---

Cargo.lock
Cargo.toml
py-rattler-build/Cargo.lock
src/main.rs
src/script/mod.rs
src/script/sandbox.rs

We will integrate with the sandbox through an external `rattler-sandbox` binary instead of embedding it in rattler-build.

chore: use rattler-sandbox as an external tool
